ioet/ioet-feature-flag

- scripts/test_import/test-import.sh
- Because now that the library is public, the import test needed to be modified to check its importability using the github repo url
- Modified `test-import.sh` to import the libary in a new poetry project
- [FF-56](https://ioetec.atlassian.net/browse/FF-56)
[FF-56]: https://ioetec.atlassian.net/browse/FF-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: FF-56 modified import library test

- scripts/test_import/test-import.sh
- Since the script is passing but if the test inside of it fails, it's not shown in the pipeline
- Added shebang in the script
- Added a variable to get the current branch so that the test imports the library from the current branch
- [FF-56](https://ioetec.atlassian.net/browse/FF-56)
N/A
[FF-56]: https://ioetec.atlassian.net/browse/FF-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FF-56 updated script to pull from current branch

- ioet_feature_flag/providers/aws_appconfig_toggle_provider.py
- ioet_feature_flag/providers/json_toggle_provider.py
- ioet_feature_flag/providers/provider.py
- ioet_feature_flag/providers/yaml_toggle_provider.py
- ioet_feature_flag/router.py
- ioet_feature_flag/strategies/cutover.py
- ioet_feature_flag/strategies/factory.py
- ioet_feature_flag/strategies/static.py
- ioet_feature_flag/strategies/strategy.py
- ioet_feature_flag/toggles.py
- pyproject.toml
- tests/providers/aws_appconfig_toggle_provider_unit_test.py
- tests/providers/json_toggle_provider_unit_test.py
- tests/providers/yaml_toggle_provider_unit_test.py
- tests/router_unit_test.py
- tests/strategies/cutover_unit_test.py
- tests/strategies/factory_unit_test.py
- tests/strategies/static_unit_test.py
- tests/toggles_unit_test.py
- Avoid giving the provider the responsibility of getting the toggle context and toggle strategies.
- A toggle router class was created with the same signature that the toggle provider used to have. And not toggle providers are only responsible of getting the toggle attributes and the list of available toggles.
- [FF-52](https://ioetec.atlassian.net/browse/FF-52)
[FF-52]: https://ioetec.atlassian.net/browse/FF-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: FF-52 refactor the toggle router

- scripts/test_import/dummy_module.py
- Because the library import test failed when #30 was merged.
- Added the context argument on the dummy module
- [FF-53](https://ioetec.atlassian.net/browse/FF-53)
[FF-53]: https://ioetec.atlassian.net/browse/FF-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FF-53 added context to dummy module for testing library import

- README.md
- pyproject.toml
- Since the repo is now public, update the documentation so users install the repo using HTTP by default
- Updated README.md accordingly. Also, removed a couple of steps just to reduce a bit of noise in the docs and make it less confusing
- [FF-64](https://ioetec.atlassian.net/browse/FF-64)
[FF-64]: https://ioetec.atlassian.net/browse/FF-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: FF-64 update readme install instructions

- scripts/test_import/test-import.sh
- Because the library should be able to be used using both poetry and pip
- Added a new function on the shell script to test the library importability in a pip project
- [FF-65](https://ioetec.atlassian.net/browse/FF-65)
N/A
[FF-65]: https://ioetec.atlassian.net/browse/FF-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: FF-65 Added library import test using pip

- .github/workflows/feature-flag-general.yaml
- scripts/test_import/test-import.sh
- Becaue se the CI pipeline has been failing due to python semantic release step not being able to push to the main branch. Also the test library import script was failing when trying to get the current branch commit hash
- Removed python semantic release from CI pipeline due to commit restrictions on main branch
- Refactored test import shell script to query the current branch just once
- [FF-74](https://ioetec.atlassian.net/browse/FF-74)
N/A
[FF-74]: https://ioetec.atlassian.net/browse/FF-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FF-74 removed semantic release from CI pipeline

- ioet_feature_flag/router.py
- ioet_feature_flag/toggles.py
- tests/router_unit_test.py
- We need a method to get the state of all the available toggles
- Created a `get_all_toggles` method for the router
- [FF-67](https://ioetec.atlassian.net/browse/FF-67)
[FF-67]: https://ioetec.atlassian.net/browse/FF-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: FF-67: get_all_toggles method

- tests/router_unit_test.py
- tests/strategies/pilot_users_unit_test.py
- Because unit tests should be isolated and not use actual dependency implementations
- Refactored the router unit test to include a dependency factory fixture and use mocks to inject to the router class being tested
- Added a dependency factory fixture on the pilot users unit test to mock a toggle context
[FF-62](https://ioetec.atlassian.net/browse/FF-62)
[FF-62]: https://ioetec.atlassian.net/browse/FF-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: FF-62 refactored unit tests to use mocks

- ioet_feature_flag/strategies/pilot_users.py
- pyproject.toml
- scripts/test_import/dummy_module.py
- scripts/test_import/dummy_test.py
- scripts/test_import/feature_toggles/feature-toggles.yaml
- tests/router_unit_test.py
- tests/strategies/factory_unit_test.py
- tests/strategies/pilot_users_unit_test.py
- Make it more convenient for the user to add multiple users to the `pilot_users` feature type
- the `allowed_users` used to be an array, and each user comma separated, but to make it easier for the user and less prone to errors, it was decided to change that string by a list.
- [FF-73](https://ioetec.atlassian.net/browse/FF-73)
[FF-73]: https://ioetec.atlassian.net/browse/FF-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: FF-73 refactor pilot users to be a list

- README.md
- Since it's needed to document every feature flag currently available, providing an example using YAML.
- Added examples for the three current feature flags available on the readme
- Added a `__init__.py` to the tests so that each file under the strategies can be individually tested using pytest
- [FF-70](https://ioetec.atlassian.net/browse/FF-70)
- [FF-71](https://ioetec.atlassian.net/browse/FF-71)
[FF-70]: https://ioetec.atlassian.net/browse/FF-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FF-71]: https://ioetec.atlassian.net/browse/FF-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: FF-70 adds examples for every FF in YAML

- usage_examples/functional_usage.md
- usage_examples/object_oriented_usage.md
Because the usage examples didn't considered what happens when a toggle router uses a single flag
- Added a note on the usage examples to remind users how to use the returned value of a flag when a single flag is needed
- Updated the functional usage example to include the same sections of the object-oriented-usage example
[FF-72](https://ioetec.atlassian.net/browse/FF-72)
N/A
[FF-72]: https://ioetec.atlassian.net/browse/FF-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: FF-72 updated usage docs

- ioet_feature_flag/router.py
- ioet_feature_flag/toggles.py
- pyproject.toml
- scripts/test_import/dummy_module.py
- scripts/test_import/dummy_test.py
- scripts/test_import/feature_toggles/feature-toggles.yaml
- tests/router_unit_test.py
- tests/toggles_unit_test.py
- usage_examples/functional_usage.md
- usage_examples/object_oriented_usage.md
- Return a boolean when only one flag name is provided to avoid confusion when using it in an `if` statement.
- Modified the toggle router to:
1. allow the user to pass a string if they only want one flag
2. return a boolean if only one flag name is provided
- Updated tests respectively
- [FF-79](https://ioetec.atlassian.net/browse/FF-79)
[FF-79]: https://ioetec.atlassian.net/browse/FF-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: FF-79 Return boolean when only one flag is provided

- ioet_feature_flag/exceptions.py
- ioet_feature_flag/strategies/pilot_users.py
- ioet_feature_flag/strategies/role_based.py
- pyproject.toml
- tests/strategies/pilot_users_unit_test.py
- tests/strategies/role_based_unit_test.py
- Because there are some feature toggles that need a context to be able to compute the toggle value properly.
- Created a new exception to be used when the toggle context is missing
- Added new unit tests on pilot users and role based FF to check the new exception is raised
- Fixed pilot users signature
- Fixed typos and removed unused parameters on tests
- [FF-80](https://ioetec.atlassian.net/browse/FF-80)
[FF-80]: https://ioetec.atlassian.net/browse/FF-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FF-80 Added new exception when context is not provided

- ioet_feature_flag/providers/json_toggle_provider.py
- ioet_feature_flag/providers/yaml_toggle_provider.py
- ioet_feature_flag/router.py
- ioet_feature_flag/toggles.py
- pyproject.toml
- scripts/test_import/dummy_module.py
- tests/conftest.py
- tests/router_unit_test.py
- tests/toggles_unit_test.py
- usage_examples/functional_usage.md
- usage_examples/object_oriented_usage.md
- Because the feature toggles are discovered correctly when called from the project root folder, but when called from a project's sub directory they are not found
- Added a new argument to the Toggles contructor to use a path as the project root folder
- Updated the router class to build the toggles location path based on the root directory recieved
- Updated the YAML and JSON providers to resolve the toggles path before reading the file
- Modified the examples to include the usage of the project root  parameter
- Added callouts to show that the param will only work when no provider is specified
- [FF-78](https://ioetec.atlassian.net/browse/FF-78)
[Screencast from 2023-11-26 15-36-22.webm](https://github.com/ioet/ioet-feature-flag/assets/67567150/8c2de9b7-ad4b-4592-aff4-b381fc3b2108) …
> fix: FF-78 made root folder selection consistent

- ioet_feature_flag/helpers/validators.py
- ioet_feature_flag/toggles.py
- tests/helpers/validators_unit_test.py
- tests/toggles_unit_test.py
- Prevent devs from bypassing the boolean validation
- Refactor validations made in if statements to a validators file
- Added validation to check if a dev if trying to bypass the boolean validation
- [FF-82](https://ioetec.atlassian.net/browse/FF-82)
[FF-82]: https://ioetec.atlassian.net/browse/FF-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: FF-82 Enhance boolean validation

- ioet_feature_flag/providers/aws_appconfig_toggle_provider.py
- ioet_feature_flag/providers/json_toggle_provider.py
- ioet_feature_flag/providers/yaml_toggle_provider.py
- ioet_feature_flag/router.py
- ioet_feature_flag/toggle_context.py
- ioet_feature_flag/toggles.py
- Make it more convenient for developers to access docstring documentation with their IDEs
- Added docstrings to functions and classes that are meant to be used externally
- [FF-86](https://ioetec.atlassian.net/browse/FF-86)
[FF-86]: https://ioetec.atlassian.net/browse/FF-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: FF-86 Add docstrings to external classes and methods

- tests/toggles_unit_test.py
- One test is not passing due to missing `project_root` argument
- Pass `project_root` as argument in the test that is failing
- [FF-82](https://ioetec.atlassian.net/browse/FF-82)
[FF-82]: https://ioetec.atlassian.net/browse/FF-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FF-82 Fix tests

- ioet_feature_flag/exceptions.py
- ioet_feature_flag/providers/file_provider.py
- ioet_feature_flag/providers/json_toggle_provider.py
- ioet_feature_flag/providers/yaml_toggle_provider.py
- pyproject.toml
- tests/providers/json_toggle_provider_unit_test.py
- tests/providers/yaml_toggle_provider_unit_test.py
- Because both JSON and YAML providers had barely difference on its implementations
- Added a new abstract class for file-based toggle providers
- Refactored yaml and json toggle providers to use the new abstract class
- Added `InvalidToggleFileFormat` exception
- [FF-63](https://ioetec.atlassian.net/browse/FF-63)
[FF-63]: https://ioetec.atlassian.net/browse/FF-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: FF-63 Implemented template method pattern

- README.md
- ioet_feature_flag/router.py
- ioet_feature_flag/toggles.py
- scripts/test_import/dummy_module.py
- tests/router_unit_test.py
- tests/toggles_unit_test.py
- usage_examples/frontend_usage.md
- usage_examples/functional_usage.md
- usage_examples/object_oriented_usage.md
- Given that some users may want to use a different file for the frontend feature flags, the documentation was updated accordingly explaining how to do it. We also took advantage to refactor the parameters of the providers.
- The providers no longer receives the `project_root` parameter. Same with the `Toggles` class.
- The documentation was updated according to the previously mentioned change.
- [FF-87](https://ioetec.atlassian.net/browse/FF-87)
[FF-87]: https://ioetec.atlassian.net/browse/FF-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: FF-87 Refactor providers

- README.md
- pyproject.toml
Because the load test spike revealed that the YAML provider is slower than the JSON one
- Updated library version in `pyproject.toml`
- [FF-61](https://ioetec.atlassian.net/browse/FF-61)
N/A
[FF-61]: https://ioetec.atlassian.net/browse/FF-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: FF-61 Updated readme considerations

- docs/architecture/c4_component_diagram.wsd
- docs/architecture/c4_system_context_diagram.wsd
- Because it was needed to have C4 diagrams of the library to document the context of the library and how it fits in the development of other applications
- Added the C4 system context diagram
- Added the C4 component diagram
https://ioetec.atlassian.net/browse/FF-51
N/A
> docs: FF-51 add C4 diagrams

- README.md
- ioet_feature_flag/providers/file_provider.py
- Improve the dev experience of developers by not having to specify a different env variable for their env to be able to use the local file provider.
- Add an optional parameter to `FileBasedProvider` to receive the current env. So for example, if their env variable is named `CURRENT_ENV`, they can pass it to the constructor of the class as `FileBasedProvider(toggles_file_path="path.json", environment=os.getenv("CURRENT_ENV"))`
- [FF-100](https://ioetec.atlassian.net/browse/FF-100)
[FF-100]: https://ioetec.atlassian.net/browse/FF-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: FF-100 Env parameter for local file provider

- .github/workflows/feature-flag-general.yaml
- scripts/test_import/test-branch-import.sh
- scripts/test_import/test-tag-import.sh
Currently, the test script that we have that checks if the library can be imported, only tests with a branch (either main or the branch of the PR). We want to test if it can import the latest tag as well.
- Added a new script to test the library import using latest tag
- Added new steps to the CI process to retrieve the latest tag and use it in tests
- https://ioetec.atlassian.net/browse/FF-98
> feat: FF-98 Update test script with tag import
